version: "3.8"
services:

  # PHP Service
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - redis

  # Redis Server
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass  "${REDIS_PASSWORD}"
    ports:
      - 6379:6379

  # Queue Server
  queue:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=queue
    working_dir: /var/www
    volumes:
      - ./:/var/www

volumes:
  db-data: ~
